### ISSUE TITLE
Any interests on helping me to recreate a new IO library? 

### ISSUE THREAD

**Issue by expnkx** [vinniefalco/json#10]
https://github.com/expnkx/fast_io/blob/master/examples/0045.blizzard_authenticator/enroll.cc

I also implement the ryu algorithm like you did.
https://github.com/expnkx/fast_io/tree/master/include/fast_io_freestanding_impl/ryu

**Comment by vinniefalco** [comment]
This requires C++20?

**Comment by expnkx** [comment]
> This requires C++20?

Yes!
C++ is awesome. No overhead of any abstraction. Easy to read code. Not much of template errors.

**Comment by vinniefalco** [comment]
C++20 isn't even available yet, and once it is available there will not be any users. I prefer to require only C++11, otherwise not many people can use the lib.

**Comment by expnkx** [comment]
> C++20 isn't even available yet, and once it is available there will not be any users. I prefer to require only C++11, otherwise not many people can use the lib.

Nope. My library is designed for C++20. Or it is not possible. All its infrastructure is based on C++20 feature concepts to make all the templates overloading work.

It is a library for the future.
Here is a MinGW GCC 10 I compiled last month. It has the std header <concepts>. You can try it with this amazing compiler :)
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

**Comment by expnkx** [comment]
Here are all the concepts this library defines.

https://github.com/expnkx/fast_io/blob/master/include/fast_io_core_impl/concept.h

**Comment by vinniefalco** [comment]
> Without C++20, it is not possible :)

There are plenty of libraries that have concepts / named requirements that only use C++11, they just don't use the C++20 syntax of concepts but SFINAE works just fine. Beast is one example, Asio is another. This seems like a gratuitous use of new language features at the expense of limiting who will be able to enjoy the library. If that's what you're into, fine, but I am not interested in that.

**Comment by expnkx** [comment]
> > Without C++20, it is not possible :)
> 
> There are plenty of libraries that have concepts / named requirements that only use C++11, they just don't use the C++20 syntax of concepts but SFINAE works just fine. Beast is one example, Asio is another. This seems like a gratuitous use of new language features at the expense of limiting who will be able to enjoy the library. If that's what you're into, fine, but I am not interested in that.

SFINAE does not work fine. Something like working with fold expression will kill you.
