### ISSUE TITLE
json::parse only returns the first digit from key-value pairs

### ISSUE THREAD

**Issue by PkmX** [vinniefalco/json#15]
The assertion

```cpp
assert(json::parse("{\"port\": 12345}").as_object().at("port").as_int64() == 12345);
```

fails as only 1 is returned.

**Comment by vinniefalco** [comment]
That's pretty lame, lol... how did this get past testing???

**Comment by vinniefalco** [comment]
I can reproduce it, thanks for a clear test case - investigating.
